options = gaoptimset('PlotFcns',...
                {@gaplotbestf,@gaplotbestindiv,@gaplotexpectation,@gaplotstopping},...
                'PopInitRange',[pi;2*pi],'Populationsize',20);
            
[x fval] = ga(@senomin,1,[],[],[],[],0,2*pi,[],options)
            
